#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
APP="$1"; IMAGE_TAG="$2"; IMAGE=$(get_app_image_name $APP $IMAGE_TAG)
verify_app_name "$APP"

output=""
for DIR in `ls /home/dokku/static_files/$APP`; do
    output="$output -v /home/dokku/static_files/$APP/$DIR/:/app/public/$DIR/"
done

echo "$output"
